# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1259, 688)
        self.line = QtWidgets.QFrame(Widget)
        self.line.setGeometry(QtCore.QRect(767, 380, 481, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Widget)
        self.line_2.setGeometry(QtCore.QRect(750, 20, 21, 651))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Image1_label = QtWidgets.QLabel(Widget)
        self.Image1_label.setGeometry(QtCore.QRect(30, 30, 681, 621))
        self.Image1_label.setObjectName("Image1_label")
        self.Image2_label = QtWidgets.QLabel(Widget)
        self.Image2_label.setGeometry(QtCore.QRect(800, 20, 411, 361))
        self.Image2_label.setObjectName("Image2_label")
        self.open_webcam_btn = QtWidgets.QPushButton(Widget)
        self.open_webcam_btn.setGeometry(QtCore.QRect(790, 470, 111, 41))
        self.open_webcam_btn.setObjectName("open_webcam_btn")
        self.submit_btn = QtWidgets.QPushButton(Widget)
        self.submit_btn.setGeometry(QtCore.QRect(790, 560, 121, 41))
        self.submit_btn.setObjectName("submit_btn")
        self.data_collect_rbtn = QtWidgets.QRadioButton(Widget)
        self.data_collect_rbtn.setGeometry(QtCore.QRect(810, 420, 110, 24))
        self.data_collect_rbtn.setObjectName("data_collect_rbtn")
        self.run_rbtn = QtWidgets.QRadioButton(Widget)
        self.run_rbtn.setGeometry(QtCore.QRect(970, 420, 110, 24))
        self.run_rbtn.setObjectName("run_rbtn")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(940, 470, 71, 41))
        self.label_3.setObjectName("label_3")
        self.name_text = QtWidgets.QLineEdit(Widget)
        self.name_text.setGeometry(QtCore.QRect(1020, 480, 131, 31))
        self.name_text.setObjectName("name_text")
        self.update_btn = QtWidgets.QPushButton(Widget)
        self.update_btn.setGeometry(QtCore.QRect(940, 560, 121, 41))
        self.update_btn.setObjectName("update_btn")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.Image1_label.setText(_translate("Widget", "Image View 1"))
        self.Image2_label.setText(_translate("Widget", "Image View 2"))
        self.open_webcam_btn.setText(_translate("Widget", "Open Webcam"))
        self.submit_btn.setText(_translate("Widget", "Submit"))
        self.data_collect_rbtn.setText(_translate("Widget", "Data Collect"))
        self.run_rbtn.setText(_translate("Widget", "Run"))
        self.label_3.setText(_translate("Widget", "Name"))
        self.update_btn.setText(_translate("Widget", "Update "))
